apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: springdemok8s
spec:
  selector:
    matchLabels:
      app: springdemok8s
  replicas: 2
  template:
    metadata:
      labels:
        app: springdemok8s
    spec:
      containers:
      - name: springdemok8s
        image: stsdemo-k8s:1.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080